### ISSUE TITLE
is there a way to publish verification results through pact broker cli tool?

### ISSUE THREAD

**Issue by praveen-em** [pact-foundation/pact_broker-client#105]
The read me file says pact broker client can be used to publish verification results but I couldn't find the right command to do this through cli tool. Or am i missing something? I see `pact-broker publish` but that is to publish pacts. Is there something similar to publish verification results? 

<img width="983" alt="Screenshot 2022-04-13 at 15 34 32" src="https://user-images.githubusercontent.com/66472747/163206185-bc1b7ba4-92c4-402e-b888-97f379f79eb3.png">

**Comment by YOU54F** [comment]
That line may be referring to the `can-i-deploy` which retrieves verification results 

https://docs.pact.io/pact_broker/client_cli/readme#can-i-deploy

but also the `pact-provider-verifier` which is packaged into the docker CLI, in the `Pact CLI Docker image` llink.


When you run the pact-verifier, you can choose whether to publish results, which is a separate [tool](https://docs.pact.io/implementation_guides/cli#provider-verifier) which doesn't appear to be referenced in that readme.

**Comment by bethesque** [comment]
Publishing the verification results is done in the verification task itself. There is no separate tool for this, because the verification results need to be published when the verification fails (and hence, the process exits with an error status). Trying to manage a separate task that only runs after the failure of a previous step would be complex to manage, so it's much simpler if the verification tool does that part itself.
