### ISSUE TITLE
Missing option to distinguish error codes for failing and missing contract verification

### ISSUE THREAD

**Issue by basiaBB** [pact-foundation/pact_broker-client#34]
I am adding contract tests to continuous delivery pipeline. There are steps to:
- run contract tests (consumer pipeline)
- publish contract (consumer pipeline)
- trigger pipeline with contract verification (provider pipeline)
- check the contract verification result (consumer pipeline)
- deploy (consumer pipeline)

I have a problem with verification the contract result because there are two options that gives exit 1 code:
- the verification is missing because provider pipeline is still running ("Missing one or more verification results")
- the verification is failed ("One or more verifications have failed")

I would like to have an option to distinguish these two cases so that I can break pipeline in case of verification failure or set retry if contract is missing (because provider is still running their tests).

Could you help me with that?

**Comment by bethesque** [comment]
Luckily enough, I've just been working in this part of the code for another issue. I'll have a think about how to make this more elegant, but in the meantime, are you comfortable using `--output json` and then parsing the result with jq? You could check the reason for the presence of `failed` or `Missing` to determine what to do.

**Comment by basiaBB** [comment]
Thanks a lot for quick response. I will use this message parsing for now and be waiting for further improvement for the future :)

**Comment by bethesque** [comment]
One thing to note is that I'm about to release a change to that resource that will make the "reason" string contain multiple, new line separated reasons, so it's possible that it may contain BOTH the words "failed" and "Missing". 

Due to the "pre-verification" feature, you should only ever have a "missing" response when you've changed the contents of the pact - if it's the same as the previous version, it will inherit the verification results. The latest version of the broker will even ignore whitespace and ordering changes, to increase the chance of a pact being pre-verified. 

Are you finding you get a "missing" often? Is contract actually changing deliberately, or is it possible that you have some random or time based data in it?

**Comment by bethesque** [comment]
Good to know. Ok, how is this:

```json
{
  "summary": {
    "deployable": null,
    "reason": "There is no verified pact between foo (3.0.0) and bar (11.0.0)",
    "success": 1,
    "failed": 0,
    "unknown": 1
  },
  "matrix": [ ...
```

You can use jq to find out if there are any unknown (missing) verification results by doing:

`pact-broker can-i-deploy --pacticipant foo --version 3.0.0 --to prod --output json | jq ".summary.unknown"`

I toyed with the idea of using different exit codes, but given that there can be different combinations of success/failed/unknown, who is to say which is the one that most people would want to know about? Would an unknown override a failure, or the other way around? 

Anyway, let me know if that would work for you.

**Comment by basiaBB** [comment]
This looks good for me :) It would be enough to query for success/failed/unknown status in the json response because it is more stable than reason message. Thank you!

**Comment by bethesque** [comment]
Cool. I've released that update in the latest gem and docker image. If you're using the DiUS hosted broker, it should be out some time today.
