### ISSUE TITLE
can-i-deploy fails on first new consumer build

### ISSUE THREAD

**Issue by Granomir** [pact-foundation/pact_broker-client#82]
I created pipeline in jenkins for building new consumer. In this pipeline after I build new consumer and publish new pact to pact-broker I invoke 'mvn pact:can-i-deploy -Dpacticipant=consumer-name -Dlatest=true' and it fails due to it's new contract not verified yet by the provider.
Is there only one way - 
1) build first time without invoking 'can-i-deploy'
2) build provider and verify new contract
3) after that build new consumer always with 'can-i-deploy' enabled
or is there a way to prevent failure for new consumer when it's contract was not verified ever?
or maybe I need to trigger building provider each time when build consumer with changed contract?

**Comment by bethesque** [comment]
> or maybe I need to trigger building provider each time when build consumer with changed contract?

Yes, you do. Have you gone through the Pact CI/CD setup guide? https://docs.pact.io/pact_nirvana Step 4 is about setting up the webhooks https://docs.pact.io/pact_nirvana/step_4

Most people don't add can-i-deploy until they've gotten the webhooks up and running.

But funnily enough, I've just implemented this for the CLI https://pact.canny.io/feature-requests/p/allow-can-i-deploy-to-run-without-returning-an-error-code

Looks like we need it for the mvn equivalent too.

This also might be relevant https://docs.pact.io/pact_nirvana/step_7#setting-up-a-pact-in-a-universal-cicd-pipeline

**Comment by cmlonder** [comment]
I also could not figure out how to automize this flow even I have webhooks to trigger provider. Here is the scenario:
* I have to create webhook first so that can i trigger my consumer with can-i-deploy
* To create the webhook, provider must exist in the broker otherwise I got an error that I try to create webhook for non existing pacticipants
* For provider to exist, I must first push some contracts to broker without can-i-deploy

So in my consumer side I can't have a pipeline without having manually push the contracts one time as Granomir mentioned the solution. Otherwise there are no any contracts in the broker so I can't create the webhook. 

* Build without can-i-deploy
* Since pacticipants now exists, create the webhook manually
* Change the pipelines to enable can-i-deploy now
* Trigger now, everything is okay

But since we have lots project, it is not easy to follow this every time.

**Comment by bethesque** [comment]
For the webhook to work, the provider build that should be triggered needs to be set up. It's not just a matter of running the default provider build - the changed pact URL needs to be passed through as per https://docs.pact.io/pact_nirvana/step_4#e-configure-pact-to-be-verified-when-contract-changes 

The webhook to trigger the provider build should be owned by the provider code, not the consumer code. If you want to automate the creation of that webhook you can use 
`pact-broker create-or-update-pacticipant --name NAME` (sorry, I need to add the docs for this) and [create-or-update-webhook](https://docs.pact.io/pact_broker/client_cli/readme/#create-or-update-webhook).

**Comment by bethesque** [comment]
Docs for create-or-update-pacticipant are here now https://docs.pact.io/pact_broker/client_cli/readme#create-or-update-pacticipant.

Looking at your TODO list, nothing in there mentions the fact that the provider has to add pact to their project, and configure the verification task, get the task passing, and add it to their own CI build. The consumer can never pass can-i-deploy until that happens.

**Comment by cmlonder** [comment]
Thanks Beth for the explanations! You are right, I forgot to mention that I have set up the broker between my provider and consumer and they are already communicating. But only manual part was adding these webhooks manually, but seems like I can set up a pipeine in provider side now and trigger it via it's consumers so my provider can register hooks for the given consumers with it's own Trigger Key. Great!
